services:
  stash-backup:
    image: ghcr.io/feederbox826/stash-backup
    container_name: stash-backup
    volumes:
     - ./stash-backup:/app/backup
    env_file:
      - .env
    environment:
      - STASH_URL=http://stash:9999
      - STASH_APIKEY=eyJ
      - CRON_SCHEDULE=*/10 * * * * # every 10 minutes